# Generated by Django 5.2.8 on 2026-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_invite", "Trip Invite"),
                    ("invite_accepted", "Invite Accepted"),
                    ("invite_declined", "Invite Declined"),
                    ("member_left", "Member Left the Trip"),
                    ("member_removed", "Member Removed from the Trip"),
                    ("trip_reminder", "Trip Reminder"),
                    ("member_joined", "Member Joined"),
                ],
                max_length=50,
            ),
        ),
    ]
